### ISSUE TITLE
Crash when annotating field without specifying size.

### ISSUE THREAD

**Issue by MutexRaceCondition** [Stuffe/isa_spec#30]
When defining an instruction with the syntax pattern `load %a:U(immediate)`, a `ValueError` is raised (`Expected a number literal`).
This is probably caused by the last line in https://github.com/Stuffe/isa_spec/blob/1f21ac176d7a9822d226c45d76f9ad51af5e5a0b/isa_spec.nim#L157-L165
Since the code does not check if there actually is a number, `get_unsigned(s)` will fail and `?` will raise the `ValueError` with the error info from `get_unsigned`.

**Comment by MutexRaceCondition** [comment]
This also happens for virtual fields, same issue but at https://github.com/Stuffe/isa_spec/blob/1f21ac176d7a9822d226c45d76f9ad51af5e5a0b/isa_spec.nim#L233

**Comment by Stuffe** [comment]
Sounds like Mega fixed it
